/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { completionsCreateCompletion } from "../funcs/completionsCreateCompletion.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Completions extends ClientSDK {
  /**
   * Creates a completion for the provided prompt and parameters.
   */
  async createCompletion(
    request: components.CreateCompletionRequest,
    options?: RequestOptions,
  ): Promise<components.CreateCompletionResponse> {
    return unwrapAsync(completionsCreateCompletion(
      this,
      request,
      options,
    ));
  }
}
