/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { embeddingsCreateEmbedding } from "../funcs/embeddingsCreateEmbedding.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Embeddings extends ClientSDK {
  /**
   * Creates an embedding vector representing the input text.
   */
  async createEmbedding(
    request: components.CreateEmbeddingRequest,
    options?: RequestOptions,
  ): Promise<components.CreateEmbeddingResponse> {
    return unwrapAsync(embeddingsCreateEmbedding(
      this,
      request,
      options,
    ));
  }
}
