/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imagesCreateImage } from "../funcs/imagesCreateImage.js";
import { imagesCreateImageEdit } from "../funcs/imagesCreateImageEdit.js";
import { imagesCreateImageVariation } from "../funcs/imagesCreateImageVariation.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Images extends ClientSDK {
  /**
   * Creates an image given a prompt.
   */
  async createImage(
    request: components.CreateImageRequest,
    options?: RequestOptions,
  ): Promise<components.ImagesResponse> {
    return unwrapAsync(imagesCreateImage(
      this,
      request,
      options,
    ));
  }

  /**
   * Creates an edited or extended image given an original image and a prompt.
   */
  async createImageEdit(
    request: components.CreateImageEditRequest,
    options?: RequestOptions,
  ): Promise<components.ImagesResponse> {
    return unwrapAsync(imagesCreateImageEdit(
      this,
      request,
      options,
    ));
  }

  /**
   * Creates a variation of a given image.
   */
  async createImageVariation(
    request: components.CreateImageVariationRequest,
    options?: RequestOptions,
  ): Promise<components.ImagesResponse> {
    return unwrapAsync(imagesCreateImageVariation(
      this,
      request,
      options,
    ));
  }
}
