workflowVersion: 1.0.0
sources:
    ArgotOpenAi-OAS:
        inputs:
            - location: openai-openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/argot/argot/argot-open-ai-oas
targets:
    argot-open-ai:
        target: typescript
        source: ArgotOpenAi-OAS
        publish:
            npm:
                token: $npm_token
