/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateVectorStoreFileBatchRequest = {
  /**
   * The ID of the vector store for which to create a File Batch.
   *
   * @remarks
   */
  vectorStoreId: string;
  createVectorStoreFileBatchRequest:
    components.CreateVectorStoreFileBatchRequest;
};

/** @internal */
export const CreateVectorStoreFileBatchRequest$inboundSchema: z.ZodType<
  CreateVectorStoreFileBatchRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  vector_store_id: z.string(),
  CreateVectorStoreFileBatchRequest:
    components.CreateVectorStoreFileBatchRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "vector_store_id": "vectorStoreId",
    "CreateVectorStoreFileBatchRequest": "createVectorStoreFileBatchRequest",
  });
});

/** @internal */
export type CreateVectorStoreFileBatchRequest$Outbound = {
  vector_store_id: string;
  CreateVectorStoreFileBatchRequest:
    components.CreateVectorStoreFileBatchRequest$Outbound;
};

/** @internal */
export const CreateVectorStoreFileBatchRequest$outboundSchema: z.ZodType<
  CreateVectorStoreFileBatchRequest$Outbound,
  z.ZodTypeDef,
  CreateVectorStoreFileBatchRequest
> = z.object({
  vectorStoreId: z.string(),
  createVectorStoreFileBatchRequest:
    components.CreateVectorStoreFileBatchRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    vectorStoreId: "vector_store_id",
    createVectorStoreFileBatchRequest: "CreateVectorStoreFileBatchRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateVectorStoreFileBatchRequest$ {
  /** @deprecated use `CreateVectorStoreFileBatchRequest$inboundSchema` instead. */
  export const inboundSchema = CreateVectorStoreFileBatchRequest$inboundSchema;
  /** @deprecated use `CreateVectorStoreFileBatchRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateVectorStoreFileBatchRequest$outboundSchema;
  /** @deprecated use `CreateVectorStoreFileBatchRequest$Outbound` instead. */
  export type Outbound = CreateVectorStoreFileBatchRequest$Outbound;
}

export function createVectorStoreFileBatchRequestToJSON(
  createVectorStoreFileBatchRequest: CreateVectorStoreFileBatchRequest,
): string {
  return JSON.stringify(
    CreateVectorStoreFileBatchRequest$outboundSchema.parse(
      createVectorStoreFileBatchRequest,
    ),
  );
}

export function createVectorStoreFileBatchRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateVectorStoreFileBatchRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateVectorStoreFileBatchRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateVectorStoreFileBatchRequest' from JSON`,
  );
}
