/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateSpeechResponse = {
  headers: { [k: string]: Array<string> };
  result: ReadableStream<Uint8Array>;
};

/** @internal */
export const CreateSpeechResponse$inboundSchema: z.ZodType<
  CreateSpeechResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.instanceof(ReadableStream<Uint8Array>),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateSpeechResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ReadableStream<Uint8Array>;
};

/** @internal */
export const CreateSpeechResponse$outboundSchema: z.ZodType<
  CreateSpeechResponse$Outbound,
  z.ZodTypeDef,
  CreateSpeechResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.instanceof(ReadableStream<Uint8Array>),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSpeechResponse$ {
  /** @deprecated use `CreateSpeechResponse$inboundSchema` instead. */
  export const inboundSchema = CreateSpeechResponse$inboundSchema;
  /** @deprecated use `CreateSpeechResponse$outboundSchema` instead. */
  export const outboundSchema = CreateSpeechResponse$outboundSchema;
  /** @deprecated use `CreateSpeechResponse$Outbound` instead. */
  export type Outbound = CreateSpeechResponse$Outbound;
}
