/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteVectorStoreFileRequest = {
  /**
   * The ID of the vector store that the file belongs to.
   */
  vectorStoreId: string;
  /**
   * The ID of the file to delete.
   */
  fileId: string;
};

/** @internal */
export const DeleteVectorStoreFileRequest$inboundSchema: z.ZodType<
  DeleteVectorStoreFileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  vector_store_id: z.string(),
  file_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "vector_store_id": "vectorStoreId",
    "file_id": "fileId",
  });
});

/** @internal */
export type DeleteVectorStoreFileRequest$Outbound = {
  vector_store_id: string;
  file_id: string;
};

/** @internal */
export const DeleteVectorStoreFileRequest$outboundSchema: z.ZodType<
  DeleteVectorStoreFileRequest$Outbound,
  z.ZodTypeDef,
  DeleteVectorStoreFileRequest
> = z.object({
  vectorStoreId: z.string(),
  fileId: z.string(),
}).transform((v) => {
  return remap$(v, {
    vectorStoreId: "vector_store_id",
    fileId: "file_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteVectorStoreFileRequest$ {
  /** @deprecated use `DeleteVectorStoreFileRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteVectorStoreFileRequest$inboundSchema;
  /** @deprecated use `DeleteVectorStoreFileRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteVectorStoreFileRequest$outboundSchema;
  /** @deprecated use `DeleteVectorStoreFileRequest$Outbound` instead. */
  export type Outbound = DeleteVectorStoreFileRequest$Outbound;
}
