/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ListInvitesRequest = {
  /**
   * A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.
   *
   * @remarks
   */
  limit?: number | undefined;
  /**
   * A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.
   *
   * @remarks
   */
  after?: string | undefined;
};

/** @internal */
export const ListInvitesRequest$inboundSchema: z.ZodType<
  ListInvitesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().int().default(20),
  after: z.string().optional(),
});

/** @internal */
export type ListInvitesRequest$Outbound = {
  limit: number;
  after?: string | undefined;
};

/** @internal */
export const ListInvitesRequest$outboundSchema: z.ZodType<
  ListInvitesRequest$Outbound,
  z.ZodTypeDef,
  ListInvitesRequest
> = z.object({
  limit: z.number().int().default(20),
  after: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListInvitesRequest$ {
  /** @deprecated use `ListInvitesRequest$inboundSchema` instead. */
  export const inboundSchema = ListInvitesRequest$inboundSchema;
  /** @deprecated use `ListInvitesRequest$outboundSchema` instead. */
  export const outboundSchema = ListInvitesRequest$outboundSchema;
  /** @deprecated use `ListInvitesRequest$Outbound` instead. */
  export type Outbound = ListInvitesRequest$Outbound;
}
