/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type RetrieveProjectServiceAccountRequest = {
  /**
   * The ID of the project.
   */
  projectId: string;
  /**
   * The ID of the service account.
   */
  serviceAccountId: string;
};

/** @internal */
export const RetrieveProjectServiceAccountRequest$inboundSchema: z.ZodType<
  RetrieveProjectServiceAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  project_id: z.string(),
  service_account_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "project_id": "projectId",
    "service_account_id": "serviceAccountId",
  });
});

/** @internal */
export type RetrieveProjectServiceAccountRequest$Outbound = {
  project_id: string;
  service_account_id: string;
};

/** @internal */
export const RetrieveProjectServiceAccountRequest$outboundSchema: z.ZodType<
  RetrieveProjectServiceAccountRequest$Outbound,
  z.ZodTypeDef,
  RetrieveProjectServiceAccountRequest
> = z.object({
  projectId: z.string(),
  serviceAccountId: z.string(),
}).transform((v) => {
  return remap$(v, {
    projectId: "project_id",
    serviceAccountId: "service_account_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RetrieveProjectServiceAccountRequest$ {
  /** @deprecated use `RetrieveProjectServiceAccountRequest$inboundSchema` instead. */
  export const inboundSchema =
    RetrieveProjectServiceAccountRequest$inboundSchema;
  /** @deprecated use `RetrieveProjectServiceAccountRequest$outboundSchema` instead. */
  export const outboundSchema =
    RetrieveProjectServiceAccountRequest$outboundSchema;
  /** @deprecated use `RetrieveProjectServiceAccountRequest$Outbound` instead. */
  export type Outbound = RetrieveProjectServiceAccountRequest$Outbound;
}
