/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type RetrieveFineTuningJobRequest = {
  /**
   * The ID of the fine-tuning job.
   *
   * @remarks
   */
  fineTuningJobId: string;
};

/** @internal */
export const RetrieveFineTuningJobRequest$inboundSchema: z.ZodType<
  RetrieveFineTuningJobRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  fine_tuning_job_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "fine_tuning_job_id": "fineTuningJobId",
  });
});

/** @internal */
export type RetrieveFineTuningJobRequest$Outbound = {
  fine_tuning_job_id: string;
};

/** @internal */
export const RetrieveFineTuningJobRequest$outboundSchema: z.ZodType<
  RetrieveFineTuningJobRequest$Outbound,
  z.ZodTypeDef,
  RetrieveFineTuningJobRequest
> = z.object({
  fineTuningJobId: z.string(),
}).transform((v) => {
  return remap$(v, {
    fineTuningJobId: "fine_tuning_job_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RetrieveFineTuningJobRequest$ {
  /** @deprecated use `RetrieveFineTuningJobRequest$inboundSchema` instead. */
  export const inboundSchema = RetrieveFineTuningJobRequest$inboundSchema;
  /** @deprecated use `RetrieveFineTuningJobRequest$outboundSchema` instead. */
  export const outboundSchema = RetrieveFineTuningJobRequest$outboundSchema;
  /** @deprecated use `RetrieveFineTuningJobRequest$Outbound` instead. */
  export type Outbound = RetrieveFineTuningJobRequest$Outbound;
}
