/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The format of the output, in one of these options: `json`, `text`, `srt`, `verbose_json`, or `vtt`.
 *
 * @remarks
 */
export const AudioResponseFormat = {
  Json: "json",
  Text: "text",
  Srt: "srt",
  VerboseJson: "verbose_json",
  Vtt: "vtt",
} as const;
/**
 * The format of the output, in one of these options: `json`, `text`, `srt`, `verbose_json`, or `vtt`.
 *
 * @remarks
 */
export type AudioResponseFormat = ClosedEnum<typeof AudioResponseFormat>;

/** @internal */
export const AudioResponseFormat$inboundSchema: z.ZodNativeEnum<
  typeof AudioResponseFormat
> = z.nativeEnum(AudioResponseFormat);

/** @internal */
export const AudioResponseFormat$outboundSchema: z.ZodNativeEnum<
  typeof AudioResponseFormat
> = AudioResponseFormat$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AudioResponseFormat$ {
  /** @deprecated use `AudioResponseFormat$inboundSchema` instead. */
  export const inboundSchema = AudioResponseFormat$inboundSchema;
  /** @deprecated use `AudioResponseFormat$outboundSchema` instead. */
  export const outboundSchema = AudioResponseFormat$outboundSchema;
}
