/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChatCompletionRequestMessageContentPartText,
  ChatCompletionRequestMessageContentPartText$inboundSchema,
  ChatCompletionRequestMessageContentPartText$Outbound,
  ChatCompletionRequestMessageContentPartText$outboundSchema,
} from "./chatcompletionrequestmessagecontentparttext.js";

export type ChatCompletionRequestToolMessageContentPart =
  ChatCompletionRequestMessageContentPartText;

/** @internal */
export const ChatCompletionRequestToolMessageContentPart$inboundSchema:
  z.ZodType<
    ChatCompletionRequestToolMessageContentPart,
    z.ZodTypeDef,
    unknown
  > = ChatCompletionRequestMessageContentPartText$inboundSchema;

/** @internal */
export type ChatCompletionRequestToolMessageContentPart$Outbound =
  ChatCompletionRequestMessageContentPartText$Outbound;

/** @internal */
export const ChatCompletionRequestToolMessageContentPart$outboundSchema:
  z.ZodType<
    ChatCompletionRequestToolMessageContentPart$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestToolMessageContentPart
  > = ChatCompletionRequestMessageContentPartText$outboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionRequestToolMessageContentPart$ {
  /** @deprecated use `ChatCompletionRequestToolMessageContentPart$inboundSchema` instead. */
  export const inboundSchema =
    ChatCompletionRequestToolMessageContentPart$inboundSchema;
  /** @deprecated use `ChatCompletionRequestToolMessageContentPart$outboundSchema` instead. */
  export const outboundSchema =
    ChatCompletionRequestToolMessageContentPart$outboundSchema;
  /** @deprecated use `ChatCompletionRequestToolMessageContentPart$Outbound` instead. */
  export type Outbound = ChatCompletionRequestToolMessageContentPart$Outbound;
}

export function chatCompletionRequestToolMessageContentPartToJSON(
  chatCompletionRequestToolMessageContentPart:
    ChatCompletionRequestToolMessageContentPart,
): string {
  return JSON.stringify(
    ChatCompletionRequestToolMessageContentPart$outboundSchema.parse(
      chatCompletionRequestToolMessageContentPart,
    ),
  );
}

export function chatCompletionRequestToolMessageContentPartFromJSON(
  jsonString: string,
): SafeParseResult<
  ChatCompletionRequestToolMessageContentPart,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ChatCompletionRequestToolMessageContentPart$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ChatCompletionRequestToolMessageContentPart' from JSON`,
  );
}
