/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The object type, which is always `organization.invite.deleted`
 */
export const InviteDeleteResponseObject = {
  OrganizationInviteDeleted: "organization.invite.deleted",
} as const;
/**
 * The object type, which is always `organization.invite.deleted`
 */
export type InviteDeleteResponseObject = ClosedEnum<
  typeof InviteDeleteResponseObject
>;

export type InviteDeleteResponse = {
  /**
   * The object type, which is always `organization.invite.deleted`
   */
  object: InviteDeleteResponseObject;
  id: string;
  deleted: boolean;
};

/** @internal */
export const InviteDeleteResponseObject$inboundSchema: z.ZodNativeEnum<
  typeof InviteDeleteResponseObject
> = z.nativeEnum(InviteDeleteResponseObject);

/** @internal */
export const InviteDeleteResponseObject$outboundSchema: z.ZodNativeEnum<
  typeof InviteDeleteResponseObject
> = InviteDeleteResponseObject$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InviteDeleteResponseObject$ {
  /** @deprecated use `InviteDeleteResponseObject$inboundSchema` instead. */
  export const inboundSchema = InviteDeleteResponseObject$inboundSchema;
  /** @deprecated use `InviteDeleteResponseObject$outboundSchema` instead. */
  export const outboundSchema = InviteDeleteResponseObject$outboundSchema;
}

/** @internal */
export const InviteDeleteResponse$inboundSchema: z.ZodType<
  InviteDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: InviteDeleteResponseObject$inboundSchema,
  id: z.string(),
  deleted: z.boolean(),
});

/** @internal */
export type InviteDeleteResponse$Outbound = {
  object: string;
  id: string;
  deleted: boolean;
};

/** @internal */
export const InviteDeleteResponse$outboundSchema: z.ZodType<
  InviteDeleteResponse$Outbound,
  z.ZodTypeDef,
  InviteDeleteResponse
> = z.object({
  object: InviteDeleteResponseObject$outboundSchema,
  id: z.string(),
  deleted: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InviteDeleteResponse$ {
  /** @deprecated use `InviteDeleteResponse$inboundSchema` instead. */
  export const inboundSchema = InviteDeleteResponse$inboundSchema;
  /** @deprecated use `InviteDeleteResponse$outboundSchema` instead. */
  export const outboundSchema = InviteDeleteResponse$outboundSchema;
  /** @deprecated use `InviteDeleteResponse$Outbound` instead. */
  export type Outbound = InviteDeleteResponse$Outbound;
}
