/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RunStepObject,
  RunStepObject$inboundSchema,
  RunStepObject$Outbound,
  RunStepObject$outboundSchema,
} from "./runstepobject.js";

export type ListRunStepsResponse = {
  object: string;
  data: Array<RunStepObject>;
  firstId: string;
  lastId: string;
  hasMore: boolean;
};

/** @internal */
export const ListRunStepsResponse$inboundSchema: z.ZodType<
  ListRunStepsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.string(),
  data: z.array(RunStepObject$inboundSchema),
  first_id: z.string(),
  last_id: z.string(),
  has_more: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "first_id": "firstId",
    "last_id": "lastId",
    "has_more": "hasMore",
  });
});

/** @internal */
export type ListRunStepsResponse$Outbound = {
  object: string;
  data: Array<RunStepObject$Outbound>;
  first_id: string;
  last_id: string;
  has_more: boolean;
};

/** @internal */
export const ListRunStepsResponse$outboundSchema: z.ZodType<
  ListRunStepsResponse$Outbound,
  z.ZodTypeDef,
  ListRunStepsResponse
> = z.object({
  object: z.string(),
  data: z.array(RunStepObject$outboundSchema),
  firstId: z.string(),
  lastId: z.string(),
  hasMore: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    firstId: "first_id",
    lastId: "last_id",
    hasMore: "has_more",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRunStepsResponse$ {
  /** @deprecated use `ListRunStepsResponse$inboundSchema` instead. */
  export const inboundSchema = ListRunStepsResponse$inboundSchema;
  /** @deprecated use `ListRunStepsResponse$outboundSchema` instead. */
  export const outboundSchema = ListRunStepsResponse$outboundSchema;
  /** @deprecated use `ListRunStepsResponse$Outbound` instead. */
  export type Outbound = ListRunStepsResponse$Outbound;
}

export function listRunStepsResponseToJSON(
  listRunStepsResponse: ListRunStepsResponse,
): string {
  return JSON.stringify(
    ListRunStepsResponse$outboundSchema.parse(listRunStepsResponse),
  );
}

export function listRunStepsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListRunStepsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRunStepsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRunStepsResponse' from JSON`,
  );
}
