/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";
import {
  Model,
  Model$inboundSchema,
  Model$Outbound,
  Model$outboundSchema,
} from "./model.js";

export const ListModelsResponseObject = {
  List: "list",
} as const;
export type ListModelsResponseObject = ClosedEnum<
  typeof ListModelsResponseObject
>;

export type ListModelsResponse = {
  object: ListModelsResponseObject;
  data: Array<Model>;
};

/** @internal */
export const ListModelsResponseObject$inboundSchema: z.ZodNativeEnum<
  typeof ListModelsResponseObject
> = z.nativeEnum(ListModelsResponseObject);

/** @internal */
export const ListModelsResponseObject$outboundSchema: z.ZodNativeEnum<
  typeof ListModelsResponseObject
> = ListModelsResponseObject$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListModelsResponseObject$ {
  /** @deprecated use `ListModelsResponseObject$inboundSchema` instead. */
  export const inboundSchema = ListModelsResponseObject$inboundSchema;
  /** @deprecated use `ListModelsResponseObject$outboundSchema` instead. */
  export const outboundSchema = ListModelsResponseObject$outboundSchema;
}

/** @internal */
export const ListModelsResponse$inboundSchema: z.ZodType<
  ListModelsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: ListModelsResponseObject$inboundSchema,
  data: z.array(Model$inboundSchema),
});

/** @internal */
export type ListModelsResponse$Outbound = {
  object: string;
  data: Array<Model$Outbound>;
};

/** @internal */
export const ListModelsResponse$outboundSchema: z.ZodType<
  ListModelsResponse$Outbound,
  z.ZodTypeDef,
  ListModelsResponse
> = z.object({
  object: ListModelsResponseObject$outboundSchema,
  data: z.array(Model$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListModelsResponse$ {
  /** @deprecated use `ListModelsResponse$inboundSchema` instead. */
  export const inboundSchema = ListModelsResponse$inboundSchema;
  /** @deprecated use `ListModelsResponse$outboundSchema` instead. */
  export const outboundSchema = ListModelsResponse$outboundSchema;
  /** @deprecated use `ListModelsResponse$Outbound` instead. */
  export type Outbound = ListModelsResponse$Outbound;
}
