/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The object type, which is always "model".
 */
export const ModelObject = {
  Model: "model",
} as const;
/**
 * The object type, which is always "model".
 */
export type ModelObject = ClosedEnum<typeof ModelObject>;

/**
 * Describes an OpenAI model offering that can be used with the API.
 */
export type Model = {
  /**
   * The model identifier, which can be referenced in the API endpoints.
   */
  id: string;
  /**
   * The Unix timestamp (in seconds) when the model was created.
   */
  created: number;
  /**
   * The object type, which is always "model".
   */
  object: ModelObject;
  /**
   * The organization that owns the model.
   */
  ownedBy: string;
};

/** @internal */
export const ModelObject$inboundSchema: z.ZodNativeEnum<typeof ModelObject> = z
  .nativeEnum(ModelObject);

/** @internal */
export const ModelObject$outboundSchema: z.ZodNativeEnum<typeof ModelObject> =
  ModelObject$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelObject$ {
  /** @deprecated use `ModelObject$inboundSchema` instead. */
  export const inboundSchema = ModelObject$inboundSchema;
  /** @deprecated use `ModelObject$outboundSchema` instead. */
  export const outboundSchema = ModelObject$outboundSchema;
}

/** @internal */
export const Model$inboundSchema: z.ZodType<Model, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    created: z.number().int(),
    object: ModelObject$inboundSchema,
    owned_by: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "owned_by": "ownedBy",
    });
  });

/** @internal */
export type Model$Outbound = {
  id: string;
  created: number;
  object: string;
  owned_by: string;
};

/** @internal */
export const Model$outboundSchema: z.ZodType<
  Model$Outbound,
  z.ZodTypeDef,
  Model
> = z.object({
  id: z.string(),
  created: z.number().int(),
  object: ModelObject$outboundSchema,
  ownedBy: z.string(),
}).transform((v) => {
  return remap$(v, {
    ownedBy: "owned_by",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Model$ {
  /** @deprecated use `Model$inboundSchema` instead. */
  export const inboundSchema = Model$inboundSchema;
  /** @deprecated use `Model$outboundSchema` instead. */
  export const outboundSchema = Model$outboundSchema;
  /** @deprecated use `Model$Outbound` instead. */
  export type Outbound = Model$Outbound;
}
