/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maximum of 512 characters long.
 *
 * @remarks
 */
export type ModifyRunRequestMetadata = {};

export type ModifyRunRequest = {
  /**
   * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maximum of 512 characters long.
   *
   * @remarks
   */
  metadata?: ModifyRunRequestMetadata | null | undefined;
};

/** @internal */
export const ModifyRunRequestMetadata$inboundSchema: z.ZodType<
  ModifyRunRequestMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type ModifyRunRequestMetadata$Outbound = {};

/** @internal */
export const ModifyRunRequestMetadata$outboundSchema: z.ZodType<
  ModifyRunRequestMetadata$Outbound,
  z.ZodTypeDef,
  ModifyRunRequestMetadata
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModifyRunRequestMetadata$ {
  /** @deprecated use `ModifyRunRequestMetadata$inboundSchema` instead. */
  export const inboundSchema = ModifyRunRequestMetadata$inboundSchema;
  /** @deprecated use `ModifyRunRequestMetadata$outboundSchema` instead. */
  export const outboundSchema = ModifyRunRequestMetadata$outboundSchema;
  /** @deprecated use `ModifyRunRequestMetadata$Outbound` instead. */
  export type Outbound = ModifyRunRequestMetadata$Outbound;
}

/** @internal */
export const ModifyRunRequest$inboundSchema: z.ZodType<
  ModifyRunRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  metadata: z.nullable(z.lazy(() => ModifyRunRequestMetadata$inboundSchema))
    .optional(),
});

/** @internal */
export type ModifyRunRequest$Outbound = {
  metadata?: ModifyRunRequestMetadata$Outbound | null | undefined;
};

/** @internal */
export const ModifyRunRequest$outboundSchema: z.ZodType<
  ModifyRunRequest$Outbound,
  z.ZodTypeDef,
  ModifyRunRequest
> = z.object({
  metadata: z.nullable(z.lazy(() => ModifyRunRequestMetadata$outboundSchema))
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModifyRunRequest$ {
  /** @deprecated use `ModifyRunRequest$inboundSchema` instead. */
  export const inboundSchema = ModifyRunRequest$inboundSchema;
  /** @deprecated use `ModifyRunRequest$outboundSchema` instead. */
  export const outboundSchema = ModifyRunRequest$outboundSchema;
  /** @deprecated use `ModifyRunRequest$Outbound` instead. */
  export type Outbound = ModifyRunRequest$Outbound;
}
