/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ProjectUserDeleteResponseObject = {
  OrganizationProjectUserDeleted: "organization.project.user.deleted",
} as const;
export type ProjectUserDeleteResponseObject = ClosedEnum<
  typeof ProjectUserDeleteResponseObject
>;

export type ProjectUserDeleteResponse = {
  object: ProjectUserDeleteResponseObject;
  id: string;
  deleted: boolean;
};

/** @internal */
export const ProjectUserDeleteResponseObject$inboundSchema: z.ZodNativeEnum<
  typeof ProjectUserDeleteResponseObject
> = z.nativeEnum(ProjectUserDeleteResponseObject);

/** @internal */
export const ProjectUserDeleteResponseObject$outboundSchema: z.ZodNativeEnum<
  typeof ProjectUserDeleteResponseObject
> = ProjectUserDeleteResponseObject$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProjectUserDeleteResponseObject$ {
  /** @deprecated use `ProjectUserDeleteResponseObject$inboundSchema` instead. */
  export const inboundSchema = ProjectUserDeleteResponseObject$inboundSchema;
  /** @deprecated use `ProjectUserDeleteResponseObject$outboundSchema` instead. */
  export const outboundSchema = ProjectUserDeleteResponseObject$outboundSchema;
}

/** @internal */
export const ProjectUserDeleteResponse$inboundSchema: z.ZodType<
  ProjectUserDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: ProjectUserDeleteResponseObject$inboundSchema,
  id: z.string(),
  deleted: z.boolean(),
});

/** @internal */
export type ProjectUserDeleteResponse$Outbound = {
  object: string;
  id: string;
  deleted: boolean;
};

/** @internal */
export const ProjectUserDeleteResponse$outboundSchema: z.ZodType<
  ProjectUserDeleteResponse$Outbound,
  z.ZodTypeDef,
  ProjectUserDeleteResponse
> = z.object({
  object: ProjectUserDeleteResponseObject$outboundSchema,
  id: z.string(),
  deleted: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProjectUserDeleteResponse$ {
  /** @deprecated use `ProjectUserDeleteResponse$inboundSchema` instead. */
  export const inboundSchema = ProjectUserDeleteResponse$inboundSchema;
  /** @deprecated use `ProjectUserDeleteResponse$outboundSchema` instead. */
  export const outboundSchema = ProjectUserDeleteResponse$outboundSchema;
  /** @deprecated use `ProjectUserDeleteResponse$Outbound` instead. */
  export type Outbound = ProjectUserDeleteResponse$Outbound;
}
