/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Usage statistics related to the run. This value will be `null` if the run is not in a terminal state (i.e. `in_progress`, `queued`, etc.).
 */
export type RunCompletionUsage = {
  /**
   * Number of completion tokens used over the course of the run.
   */
  completionTokens: number;
  /**
   * Number of prompt tokens used over the course of the run.
   */
  promptTokens: number;
  /**
   * Total number of tokens used (prompt + completion).
   */
  totalTokens: number;
};

/** @internal */
export const RunCompletionUsage$inboundSchema: z.ZodType<
  RunCompletionUsage,
  z.ZodTypeDef,
  unknown
> = z.object({
  completion_tokens: z.number().int(),
  prompt_tokens: z.number().int(),
  total_tokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "completion_tokens": "completionTokens",
    "prompt_tokens": "promptTokens",
    "total_tokens": "totalTokens",
  });
});

/** @internal */
export type RunCompletionUsage$Outbound = {
  completion_tokens: number;
  prompt_tokens: number;
  total_tokens: number;
};

/** @internal */
export const RunCompletionUsage$outboundSchema: z.ZodType<
  RunCompletionUsage$Outbound,
  z.ZodTypeDef,
  RunCompletionUsage
> = z.object({
  completionTokens: z.number().int(),
  promptTokens: z.number().int(),
  totalTokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    completionTokens: "completion_tokens",
    promptTokens: "prompt_tokens",
    totalTokens: "total_tokens",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunCompletionUsage$ {
  /** @deprecated use `RunCompletionUsage$inboundSchema` instead. */
  export const inboundSchema = RunCompletionUsage$inboundSchema;
  /** @deprecated use `RunCompletionUsage$outboundSchema` instead. */
  export const outboundSchema = RunCompletionUsage$outboundSchema;
  /** @deprecated use `RunCompletionUsage$Outbound` instead. */
  export type Outbound = RunCompletionUsage$Outbound;
}

export function runCompletionUsageToJSON(
  runCompletionUsage: RunCompletionUsage,
): string {
  return JSON.stringify(
    RunCompletionUsage$outboundSchema.parse(runCompletionUsage),
  );
}

export function runCompletionUsageFromJSON(
  jsonString: string,
): SafeParseResult<RunCompletionUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RunCompletionUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunCompletionUsage' from JSON`,
  );
}
