/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";
import {
  StaticChunkingStrategy,
  StaticChunkingStrategy$inboundSchema,
  StaticChunkingStrategy$Outbound,
  StaticChunkingStrategy$outboundSchema,
} from "./staticchunkingstrategy.js";

/**
 * Always `static`.
 */
export const StaticChunkingStrategyResponseParamType = {
  Static: "static",
} as const;
/**
 * Always `static`.
 */
export type StaticChunkingStrategyResponseParamType = ClosedEnum<
  typeof StaticChunkingStrategyResponseParamType
>;

export type StaticChunkingStrategyResponseParam = {
  /**
   * Always `static`.
   */
  type: StaticChunkingStrategyResponseParamType;
  static: StaticChunkingStrategy;
};

/** @internal */
export const StaticChunkingStrategyResponseParamType$inboundSchema:
  z.ZodNativeEnum<typeof StaticChunkingStrategyResponseParamType> = z
    .nativeEnum(StaticChunkingStrategyResponseParamType);

/** @internal */
export const StaticChunkingStrategyResponseParamType$outboundSchema:
  z.ZodNativeEnum<typeof StaticChunkingStrategyResponseParamType> =
    StaticChunkingStrategyResponseParamType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StaticChunkingStrategyResponseParamType$ {
  /** @deprecated use `StaticChunkingStrategyResponseParamType$inboundSchema` instead. */
  export const inboundSchema =
    StaticChunkingStrategyResponseParamType$inboundSchema;
  /** @deprecated use `StaticChunkingStrategyResponseParamType$outboundSchema` instead. */
  export const outboundSchema =
    StaticChunkingStrategyResponseParamType$outboundSchema;
}

/** @internal */
export const StaticChunkingStrategyResponseParam$inboundSchema: z.ZodType<
  StaticChunkingStrategyResponseParam,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: StaticChunkingStrategyResponseParamType$inboundSchema,
  static: StaticChunkingStrategy$inboundSchema,
});

/** @internal */
export type StaticChunkingStrategyResponseParam$Outbound = {
  type: string;
  static: StaticChunkingStrategy$Outbound;
};

/** @internal */
export const StaticChunkingStrategyResponseParam$outboundSchema: z.ZodType<
  StaticChunkingStrategyResponseParam$Outbound,
  z.ZodTypeDef,
  StaticChunkingStrategyResponseParam
> = z.object({
  type: StaticChunkingStrategyResponseParamType$outboundSchema,
  static: StaticChunkingStrategy$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StaticChunkingStrategyResponseParam$ {
  /** @deprecated use `StaticChunkingStrategyResponseParam$inboundSchema` instead. */
  export const inboundSchema =
    StaticChunkingStrategyResponseParam$inboundSchema;
  /** @deprecated use `StaticChunkingStrategyResponseParam$outboundSchema` instead. */
  export const outboundSchema =
    StaticChunkingStrategyResponseParam$outboundSchema;
  /** @deprecated use `StaticChunkingStrategyResponseParam$Outbound` instead. */
  export type Outbound = StaticChunkingStrategyResponseParam$Outbound;
}
